version: "2" 
services:
  # name container/service 
  noveesoft-apache-php:
    # dockerfile location 
    build: . 
    ports: 
      - "50080:50080"
      - "50022:50022"
    volumes:
      - ./sites:/var/sites
      - ./logs:/var/logs
    #network_mode: host
    #dns:
    # - 8.8.8.8
    # - 8.8.4.4    
    #networks:
    #  testing_net:
    #    ipv4_address: 192.168.2.200

#networks:
#  testing_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 255.255.255.0
#          gateway: 192.168.2.1 
