version: "3.2" 
services:
  # name container/service 
  noveesoft-apache-php:
    # dockerfile location 
    build: . 
    ports: 
      - "50080:50080"
      - "50022:50022"
    volumes:
      - /var/www:/mnt/synology-kierkels
      #- "nfsmountCC:/mnt/synology-kierkels"
    #network_mode: host
    #dns:
    # - 8.8.8.8
    # - 8.8.4.4    
    #networks:
    #  testing_net:
    #    ipv4_address: 192.168.2.200

#volumes:
#  nfsmountCC:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: "addr=192.168.2.200"
#      device: ":/volume1/vm/noveesoft/"

#networks:
#  testing_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 255.255.255.0
#          gateway: 192.168.2.1 
