version: "2" 
services:
  # name container/service 
  noveesoft-apache-php:
    # dockerfile location 
    build: . 
    ports: 
      - "8080:80"
    volumes:
      - ./sites:/var/sites    
    networks:
      testing_net:
        ipv4_address: 192.168.100.200

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.1/24